### ISSUE TITLE
Errors find when calling `discovery_user_medias`

### ISSUE THREAD

**Issue by diavy** [sns-sdks/python-facebook#49]
HI, when I run the following codes to get all the posts by user @dior, 
`api = IgProApi(APP_ID, SECRET, long_term_token=LONG_TERM_TOKEN,
               instagram_business_id=INSTAGRAM_BUSINESS_ID,
              sleep_on_rate_limit=True)
api.discovery_user_medias(username='dior', since_time=None, count=None, limit=500)`

Then I found the following errors:
**Traceback (most recent call last):
  File "/Users/xshuai/Documents/Projects/wissee_dev_old/projects/alba_capital/instagram_analysis/ig_api_extraction.py", line 35, in <module>
    media = api.discovery_user_medias(username=query, since_time=None, count=None, limit=500)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/instagram.py", line 151, in discovery_user_medias
    business_discovery=True
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/instagram.py", line 231, in paged_by_cursor
    data = self._parse_response(resp)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/base.py", line 216, in _parse_response
    self._check_graph_error(data)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/base.py", line 230, in _check_graph_error
    raise PyFacebookException(error_data)
pyfacebook.error.PyFacebookException: FacebookException(code=1,type=None,message=Please reduce the amount of data you're asking for, then retry your request)**

Could you please take a look at the problematic codes? thanks!

**Comment by MerleLiuKun** [comment]
Hey, As the error says, this data size is too big. You should reduce the limit count. such as 100.

As I see，this may be depend on the data size. So this not have a exect count.:)

**Comment by diavy** [comment]
HI, I tried to reduce the limit to 100 (previously I used 500), and found the following error:

Traceback (most recent call last):
  File "/Users/xshuai/Documents/Projects/wissee_dev_old/projects/alba_capital/instagram_analysis/ig_api_extraction.py", line 35, in <module>
    media = api.discovery_user_medias(username=query, since_time=None, count=None, limit=100)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/instagram.py", line 151, in discovery_user_medias
    business_discovery=True
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/instagram.py", line 231, in paged_by_cursor
    data = self._parse_response(resp)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/base.py", line 216, in _parse_response
    self._check_graph_error(data)
  File "/usr/local/lib/python3.7/site-packages/pyfacebook/api/base.py", line 230, in _check_graph_error
    raise PyFacebookException(error_data)
pyfacebook.error.PyFacebookException: FacebookException(code=1,type=None,message=An unknown error occurred)

**Comment by MerleLiuKun** [comment]
Oh, I have tried more times. with the page `dior`,  I found that this have too many media with type `CAROUSEL_ALBUM`(multi photos), So with the default fields the body size is too big.

If you still want use default fields, you should set more small limit, I have tried 50 is ok.

If you just use some main fields, such as caption,comment_count,like_count, You can set the parameter `fields` with `caption,comments_count,id,like_count,media_type`, now limit is 100 also ok.

**Comment by diavy** [comment]
That's very helpful! To specify the "fields" argument seems to solve the issue. thanks! I will let you know if there's other issue.

**Comment by MerleLiuKun** [comment]
Very happy for your use. Welcome for your feedback.
